### PR TITLE
Fixed some things in its code

### PR DESCRIPTION
**Pull request by Zero3K**
I fixed some things in its code (such as misspellings and grammar issues).

### CODE REVIEW

**Comment by maxrigout** [comment]
I've just fixed all of these issues already. Thanks for your help

**Comment by Zero3K** [comment]
"Removed the rest of the spaces before colons" and "Changed usage of nb to understandable terms" should still be merged.

**Comment by maxrigout** [comment]
no. I just removed the last "nb" abbreviation. The other "spaces before colons" are not grammatical errors.
This is code, not an essay. The only time the space before the colon error matters is in strings aka anything between double quotes.

**Comment by Zero3K** [comment]
Okay.

**Pull request closed without merging**
